model_name: colbert-ir/colbertv2.0
language: en
task: contrastive
train_file: ./data/train_data/English_train_data.json
eval_file: ./data/train_data/English_val_data.json
max_seq_length: 128
margin: 0.25
batch_size: 1
lr: 0.00005
max_grad_norm: 1.0
device: cuda
distributed: false
patience: 5
log_dir: ./logs/contrastive_colbert/
epochs: 5
loss_fn: cosine
num_neg_samples: 3

