model_name: bert-base-uncased
language: en
task: classification
num_labels: 3
train_file: ./data/preprocessed/English_train.json
eval_file: ./data/preprocessed/English_dev.json
max_seq_length: 256
output_dir: ./output/classification/
epochs: 1.25
batch_size: 1
warmup_steps: 10
weight_decay: 0.01
logging_steps: 10
eval_steps: 10
save_steps: 10
save_total_limit: 2
load_best_model_at_end: true
metric_for_best_model: eval_loss
greater_is_better: false
learning_rate: 0.000005
lr_schedular_type: constant