model_name: bert-base-uncased
language: en
task: contrastive
train_file: ./data/preprocessed/English_train.json
eval_file: ./data/preprocessed/English_dev.json
max_seq_length: 128
margin: 0.5
batch_size: 1
lr: 0.00001
max_grad_norm: 1.0
device: cuda
distributed: false
patience: 5
log_dir: ./logs/classification/
epochs: 5
num_labels: 3

