exp_name: en_rac_softk
model_name: bert-base-uncased
retriever_path: ./logs/joint_maxsim_freeze_retri_train_cls/checkpoints/retriever
classifier_path: ./logs/joint_maxsim_freeze_retri_train_cls/checkpoints/classifier
output_file_retriever: ./results/en/en_rac_softk.txt
output_file_classifier: ./results/en/en_rac_softk.json
data_file: ./data/main/English_test.json
language: en
max_length: 128
top_k: 5
meta_file: ./meta.json
num_labels: 3
score_fn: maxsim