exp_name: test7
model_name: bert-base-uncased
retriever_path: ./logs/test7/checkpoints/retriever
classifier_path: ./logs/test7/checkpoints/classifier
output_file_retriever: ./results/test7.txt
output_file_classifier: ./results/test7.json
data_file: ./data/main/English_dev.json
language: en
max_length: 128
top_k: 5
meta_file: ./data/preprocessed/meta.json
num_labels: 3
score_fn: maxsim